spring.application.name=catch-service
spring.datasource.url=jdbc:postgresql://localhost:5432/anglerystDB
spring.datasource.username=ds
spring.datasource.password=REDACTED
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=REDACTED
jwt.expiration=86400000
server.port=8091
