spring.application.name=user-service
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/anglerystDB}
spring.datasource.username=${DB_USERNAME:ds}
spring.datasource.password=${DB_PASSWORD:REDACTED}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:REDACTED}
jwt.expiration=86400000
server.port=8090
